/// Action names of the journal in words (the same wording as the web panel, apps/web/src/lib/permissions.ts).
const auditLabelsRu = <String, String>{
  "user.create": "Создан(а)",
  "user.update": "Изменены данные",
  "user.deactivate": "Отключён(а)",
  "user.reactivate": "Восстановлен(а)",
  "user.role_change": "Изменена роль",
  "user.permission_change": "Изменены права",
  "user.password_reset": "Пароль задан администратором",
  "user.password_change": "Сменил(а) свой пароль",
  "user.name_change": "Изменил(а) своё имя",
  "user.location_visibility": "Изменена видимость на карте",
  "user.bootstrap": "Создан первый администратор",
  "audit.clear": "Журнал очищен",
  "material.delete": "Удалён материал",
  "kit_template.delete": "Удалён комплект",
  "admin.bootstrap": "Создан первый администратор",
  "user.promote_to_super_admin": "Назначен главным администратором",
  "auth.login": "Вход в систему",
  "auth.refresh_reuse_detected": "Подозрительный повторный вход — сессия закрыта",
  "worker.register": "Новая заявка мастерицы",
  "worker.approve": "Мастерица одобрена",
  "worker.invite": "Приглашение мастерице",
  "worker.invite_revoke": "Приглашение отменено",
  "worker.invite_accepted": "Мастерица пришла по приглашению",
  "worker.delete": "Мастерица удалена",
  "worker.reject": "Заявка отклонена",
  "worker.update": "Изменена карточка мастерицы",
  "worker.assign_manager": "Сменён менеджер",
  "worker.location_update": "Обновлено местоположение",
  "worker.telegram_linked": "Привязан Telegram",
  "worker.telegram_login_success": "Вход мастерицы через Telegram",
  "worker.telegram_login_failed": "Неудачный вход через Telegram",
  "worker.telegram_handoff_consumed": "Использована ссылка входа из Telegram",
  "collateral.receive": "Залог принят",
  "collateral.return": "Залог возвращён",
  "collateral.photo_add": "Добавлено фото залога",
  "assignment.create": "Выдана работа",
  "delivery.complete": "Материалы доставлены",
  "handoff.started": "Начата передача работы",
  "handoff.worker_scanned": "Мастерица отсканировала QR",
  "handoff.confirmed": "Мастерица подтвердила получение",
  "handoff.problem": "Мастерица сообщила о проблеме",
  "delivery.pickup": "Работа забрана",
  "work.progress": "Мастерица обновила прогресс",
  "work.ready_for_pickup": "Работа готова",
  "quality.inspect": "Работа принята",
  "cash_payment.create": "Выплата наличными",
  "stock.movement": "Движение по складу",
  "material.create": "Добавлен материал",
  "material.update": "Изменён материал",
  "kit.create": "Создан комплект",
  "kit.update": "Изменён комплект",
  "kit.assemble": "Собраны комплекты",
  "color.create": "Добавлен цвет",
  "color.update": "Изменён цвет",
  "catalog.create": "Добавлена работа в каталог",
  "catalog.update": "Изменена работа в каталоге",
  "catalog.delete": "Удалена работа из каталога",
  "catalog.media_add": "Добавлено фото в каталог",
  "catalog.status_change": "Изменён статус работы в каталоге",
  "catalog.variant_add": "Добавлен цвет к модели",
  "pay_rate.change": "Изменена ставка за 9 м",
  "settings.company_contact": "Изменены контакты компании",
};

/// A readable action name; an unknown (new) action falls back to its code rather than to nothing.
String auditLabel(String action) => auditLabelsRu[action] ?? action;
