/** Human names of permission codes (same words as the mobile app). Codes never reach the owner's eyes. */
export const PERMISSION_LABELS: Record<string, string> = {
  USER_VIEW_ALL: 'Видеть сотрудников',
  USER_CREATE: 'Добавлять сотрудников',
  USER_UPDATE: 'Изменять данные сотрудников',
  USER_DEACTIVATE: 'Отключать сотрудников',
  ROLE_ASSIGN: 'Менять роли',
  PERMISSION_MANAGE: 'Настраивать права',
  WORKER_VIEW_ALL: 'Видеть всех мастериц',
  WORKER_VIEW_ASSIGNED: 'Видеть своих мастериц',
  WORKER_APPROVE: 'Одобрять заявки',
  WORKER_UPDATE: 'Изменять карточку мастерицы',
  WORKER_ASSIGN_MANAGER: 'Назначать менеджера',
  COLLATERAL_VIEW: 'Видеть залог',
  COLLATERAL_MANAGE: 'Принимать и возвращать залог',
  ASSIGNMENT_VIEW_ALL: 'Видеть все задания',
  ASSIGNMENT_VIEW_ASSIGNED: 'Видеть задания своих мастериц',
  ASSIGNMENT_CREATE: 'Выдавать работу',
  ASSIGNMENT_ACCEPT: 'Принимать работу',
  FINANCE_VIEW_ALL: 'Видеть все начисления',
  FINANCE_VIEW_ASSIGNED: 'Видеть начисления своих мастериц',
  CASH_PAYOUT: 'Выплачивать наличными',
  PROFIT_VIEW: 'Видеть прибыль',
  CATALOG_VIEW: 'Видеть каталог',
  CATALOG_MANAGE: 'Изменять каталог',
  INVENTORY_VIEW: 'Видеть склад',
  INVENTORY_MANAGE: 'Приход и комплекты',
  MAP_VIEW_ALL: 'Карта: все',
  MAP_VIEW_ASSIGNED: 'Карта: свои мастерицы',
  LIVE_LOCATION_VIEW_ALL: 'Геолокация: все',
  LIVE_LOCATION_VIEW_ASSIGNED: 'Геолокация: свои мастерицы',
  PAY_RATE_MANAGE: 'Менять цену за 9 м',
  SETTINGS_MANAGE: 'Настройки компании',
  AUDIT_VIEW: 'Видеть журнал действий',
};

export const PERMISSION_GROUPS: { title: string; perms: string[] }[] = [
  { title: 'Пользователи', perms: ['USER_VIEW_ALL', 'USER_CREATE', 'USER_UPDATE', 'USER_DEACTIVATE', 'ROLE_ASSIGN', 'PERMISSION_MANAGE'] },
  { title: 'Мастерицы', perms: ['WORKER_VIEW_ALL', 'WORKER_VIEW_ASSIGNED', 'WORKER_APPROVE', 'WORKER_UPDATE', 'WORKER_ASSIGN_MANAGER'] },
  { title: 'Залог', perms: ['COLLATERAL_VIEW', 'COLLATERAL_MANAGE'] },
  { title: 'Задания', perms: ['ASSIGNMENT_VIEW_ALL', 'ASSIGNMENT_VIEW_ASSIGNED', 'ASSIGNMENT_CREATE', 'ASSIGNMENT_ACCEPT'] },
  { title: 'Выплаты и деньги', perms: ['FINANCE_VIEW_ALL', 'FINANCE_VIEW_ASSIGNED', 'CASH_PAYOUT', 'PROFIT_VIEW'] },
  { title: 'Каталог', perms: ['CATALOG_VIEW', 'CATALOG_MANAGE'] },
  { title: 'Склад', perms: ['INVENTORY_VIEW', 'INVENTORY_MANAGE'] },
  { title: 'Карта', perms: ['MAP_VIEW_ALL', 'MAP_VIEW_ASSIGNED', 'LIVE_LOCATION_VIEW_ALL', 'LIVE_LOCATION_VIEW_ASSIGNED'] },
  { title: 'Настройки', perms: ['PAY_RATE_MANAGE', 'SETTINGS_MANAGE'] },
  { title: 'Журнал действий', perms: ['AUDIT_VIEW'] },
];

export const AUDIT_USER_LABELS: Record<string, string> = {
  'user.create': 'Создан(а)',
  'user.update': 'Изменены данные',
  'user.deactivate': 'Отключён(а)',
  'user.reactivate': 'Восстановлен(а)',
  'user.role_change': 'Изменена роль',
  'user.permission_change': 'Изменены права',
  'user.password_reset': 'Выдан новый пароль',
};
